### ISSUE TITLE
Error: Cannot find module '/Users/Username/deposit.js'

### ISSUE THREAD

**Issue by d4much** [Eclipse-Laboratories-Inc/eclipse-deposit#11]
Hi I am on mac os x 11.6 and following the installation process thoroghly
I used homebrew to install nodes.js
however it seems nodes.js is missing a package or was installed in the wrong path?

Please can you direct me as I am a complete idiot when it comes to cli. Thank you!

Detailed error message:

Node.js v20.11.1
much@Michaels-Air ~ % node deposit.js
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/Users/much/deposit.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.11.1
much@Michaels-Air ~ % yarn --version
1.22.21

**Comment by rollquaye** [comment]
you got any solution for this?

**Comment by duongnq2798** [comment]
I've created a repository that ensures a seamless experience without the need for any code editing
Check here: https://github.com/duongnq2798/testnet-deposit/tree/feat-deposit-cli
