### ISSUE TITLE
not recognized internal or external command

### ISSUE THREAD

**Issue by ankushn22** [Eclipse-Laboratories-Inc/eclipse-deposit#17]
Hello I am getting this error with this command. how to solve

C:\Windows\system32>git clone https://github.com/Eclipse-Laboratories-Inc/testnet-deposit
'git' is not recognized as an internal or external command,
operable program or batch file.

**Comment by sivaaprs** [comment]
same problem any one please help us

**Comment by Aryankhura** [comment]
Same problem how to solve this

**Comment by rollquaye** [comment]
> Hello I am getting this error with this command. how to solve
> 
> C:\Windows\system32>git clone https://github.com/Eclipse-Laboratories-Inc/testnet-deposit 'git' is not recognized as an internal or external command, operable program or batch file.


You need to run the command in linux terminal
