### ISSUE TITLE
node deposit.js [YOUR_SOLANA_ADDRESS] 0x7C9e161ebe55000a3220F972058Fb83273653a6e [AMOUNT_IN_GWEI] [FEE_IN_GWEI] [ETHEREUM_PRIVATE_KEY] https://rpc.sepolia.org

### ISSUE THREAD

**Issue by Brownbehaviour** [Eclipse-Laboratories-Inc/eclipse-deposit#5]

**Comment by samboluy** [comment]
Hi, you need to replace those information inside the square bracket to your own wallet address, and it should work

**Comment by duongnq2798** [comment]
I've created a repository that ensures a seamless experience without the need for any code editing
https://github.com/duongnq2798/testnet-deposit/tree/feat-deposit-cli
