### ISSUE TITLE
Issues deploying contract using windows

### ISSUE THREAD

**Issue by TRIBUNALS2** [Eclipse-Laboratories-Inc/eclipse-deposit#7]
Iys quite challenging to deploy contract using a windows pc. The guide speaks mostly using Linux, which not everyone is familiar with as a user not developer

**Comment by enolife** [comment]
> Iys quite challenging to deploy contract using a windows pc. The guide speaks mostly using Linux, which not everyone is familiar with as a user not developer

Google "WSL Windows"
